name: Waka Readme

on:
  workflow_dispatch:
  
  schedule:
    # Runs at 08:00 UTC
    - cron: "0 8 * * *"
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_UPDATED_DATE: True
          # Others
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_LOC_CHART: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_PROFILE_VIEWS: False
          SHOW_SHORT_INFO: False
          LOCALE: en
          COMMIT_BY_ME: False
          COMMIT_MESSAGE: Updated with Dev Metrics
          SHOW_TOTAL_CODE_TIME: True
